<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Plugin;
use Illuminate\Support\Facades\DB;

class PluginSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('plugins')->delete();

        $plugins = [
            // Core Functionality - Altijd actief
            [
                'name' => 'dashboard',
                'display_name' => 'Dashboard',
                'description' => 'Main dashboard with overview statistics and quick actions',
                'icon' => 'fas fa-tachometer-alt',
                'category' => 'core',
                'is_active' => true,
                'is_core' => true,
                'dependencies' => [],
                'routes' => ['dashboard'],
                'permissions' => null,
                'sort_order' => 1,
                'version' => '1.0.0',
                'author' => 'AdCompro',
            ],
            [
                'name' => 'companies',
                'display_name' => 'Companies',
                'description' => 'Manage multiple companies and their settings',
                'icon' => 'fas fa-building',
                'category' => 'core',
                'is_active' => true,
                'is_core' => true,
                'dependencies' => [],
                'routes' => ['companies'],
                'permissions' => ['super_admin', 'admin'],
                'sort_order' => 2,
                'version' => '1.0.0',
                'author' => 'AdCompro',
            ],
            [
                'name' => 'users',
                'display_name' => 'User Management',
                'description' => 'Manage users, roles and permissions',
                'icon' => 'fas fa-user-cog',
                'category' => 'core',
                'is_active' => true,
                'is_core' => true,
                'dependencies' => ['companies'],
                'routes' => ['users'],
                'permissions' => ['super_admin', 'admin'],
                'sort_order' => 3,
                'version' => '1.0.0',
                'author' => 'AdCompro',
            ],

            // Productivity Tools
            [
                'name' => 'projects',
                'display_name' => 'Projects',
                'description' => 'Complete project management with milestones, tasks and subtasks',
                'icon' => 'fas fa-project-diagram',
                'category' => 'productivity',
                'is_active' => true,
                'is_core' => false,
                'dependencies' => ['customers'],
                'routes' => ['projects', 'project-milestones', 'project-tasks', 'project-subtasks'],
                'permissions' => null,
                'sort_order' => 10,
                'version' => '2.0.0',
                'author' => 'AdCompro',
            ],
            [
                'name' => 'time_tracking',
                'display_name' => 'Time Tracking',
                'description' => 'Track time spent on projects with approval workflow',
                'icon' => 'fas fa-clock',
                'category' => 'productivity',
                'is_active' => true,
                'is_core' => false,
                'dependencies' => ['projects'],
                'routes' => ['time-entries'],
                'permissions' => null,
                'sort_order' => 11,
                'version' => '1.5.0',
                'author' => 'AdCompro',
            ],
            [
                'name' => 'calendar',
                'display_name' => 'Calendar',
                'description' => 'Calendar integration with Microsoft 365 sync',
                'icon' => 'fas fa-calendar-alt',
                'category' => 'productivity',
                'is_active' => true,
                'is_core' => false,
                'dependencies' => [],
                'routes' => ['calendar'],
                'permissions' => null,
                'sort_order' => 12,
                'version' => '1.2.0',
                'author' => 'AdCompro',
            ],
            [
                'name' => 'templates',
                'display_name' => 'Milestone Templates',
                'description' => 'Create and manage project milestone templates',
                'icon' => 'fas fa-copy',
                'category' => 'productivity',
                'is_active' => true,
                'is_core' => false,
                'dependencies' => ['projects'],
                'routes' => ['project-templates'],
                'permissions' => null,
                'sort_order' => 13,
                'version' => '1.0.0',
                'author' => 'AdCompro',
            ],
            [
                'name' => 'services',
                'display_name' => 'Service Packages',
                'description' => 'Manage service packages that can be imported into projects',
                'icon' => 'fas fa-box',
                'category' => 'productivity',
                'is_active' => true,
                'is_core' => false,
                'dependencies' => ['service_categories'],
                'routes' => ['services'],
                'permissions' => null,
                'sort_order' => 14,
                'version' => '1.1.0',
                'author' => 'AdCompro',
            ],
            [
                'name' => 'service_categories',
                'display_name' => 'Service Categories',
                'description' => 'Organize services into categories',
                'icon' => 'fas fa-tags',
                'category' => 'productivity',
                'is_active' => true,
                'is_core' => false,
                'dependencies' => [],
                'routes' => ['service-categories'],
                'permissions' => null,
                'sort_order' => 15,
                'version' => '1.0.0',
                'author' => 'AdCompro',
            ],

            // Financial & Billing
            [
                'name' => 'invoices',
                'display_name' => 'Invoices',
                'description' => 'Complete invoicing system with automatic generation',
                'icon' => 'fas fa-file-invoice',
                'category' => 'financial',
                'is_active' => true,
                'is_core' => false,
                'dependencies' => ['projects', 'customers'],
                'routes' => ['invoices'],
                'permissions' => ['super_admin', 'admin'],
                'sort_order' => 20,
                'version' => '1.8.0',
                'author' => 'AdCompro',
            ],
            [
                'name' => 'invoice_templates',
                'display_name' => 'Invoice Templates',
                'description' => 'Design custom invoice templates with drag & drop builder',
                'icon' => 'fas fa-file-contract',
                'category' => 'financial',
                'is_active' => true,
                'is_core' => false,
                'dependencies' => ['invoices'],
                'routes' => ['invoice-templates'],
                'permissions' => ['super_admin', 'admin'],
                'sort_order' => 21,
                'version' => '1.3.0',
                'author' => 'AdCompro',
            ],
            [
                'name' => 'budget_tracking',
                'display_name' => 'Budget Tracking',
                'description' => 'Track project budgets with rollover functionality',
                'icon' => 'fas fa-chart-line',
                'category' => 'financial',
                'is_active' => true,
                'is_core' => false,
                'dependencies' => ['projects', 'time_tracking'],
                'routes' => [],
                'permissions' => null,
                'sort_order' => 22,
                'version' => '1.0.0',
                'author' => 'AdCompro',
            ],

            // CRM
            [
                'name' => 'customers',
                'display_name' => 'Customers',
                'description' => 'Customer relationship management',
                'icon' => 'fas fa-users',
                'category' => 'communication',
                'is_active' => true,
                'is_core' => false,
                'dependencies' => ['companies'],
                'routes' => ['customers'],
                'permissions' => null,
                'sort_order' => 30,
                'version' => '1.5.0',
                'author' => 'AdCompro',
            ],
            [
                'name' => 'contacts',
                'display_name' => 'Contacts',
                'description' => 'Manage contact persons for customers',
                'icon' => 'fas fa-address-book',
                'category' => 'communication',
                'is_active' => true,
                'is_core' => false,
                'dependencies' => ['customers'],
                'routes' => ['contacts'],
                'permissions' => null,
                'sort_order' => 31,
                'version' => '1.2.0',
                'author' => 'AdCompro',
            ],

            // Reporting
            [
                'name' => 'reports',
                'display_name' => 'Reports',
                'description' => 'Generate various reports and analytics',
                'icon' => 'fas fa-chart-bar',
                'category' => 'reporting',
                'is_active' => false,
                'is_core' => false,
                'dependencies' => ['projects'],
                'routes' => ['reports'],
                'permissions' => ['super_admin', 'admin', 'project_manager'],
                'sort_order' => 40,
                'version' => '0.9.0',
                'author' => 'AdCompro',
            ],
            [
                'name' => 'exports',
                'display_name' => 'Data Exports',
                'description' => 'Export data to Excel, PDF and CSV formats',
                'icon' => 'fas fa-file-export',
                'category' => 'reporting',
                'is_active' => false,
                'is_core' => false,
                'dependencies' => [],
                'routes' => [],
                'permissions' => ['super_admin', 'admin'],
                'sort_order' => 41,
                'version' => '0.5.0',
                'author' => 'AdCompro',
            ],

            // System
            [
                'name' => 'settings',
                'display_name' => 'Settings',
                'description' => 'System-wide configuration and preferences',
                'icon' => 'fas fa-cog',
                'category' => 'general',
                'is_active' => true,
                'is_core' => false,
                'dependencies' => [],
                'routes' => ['settings'],
                'permissions' => ['super_admin', 'admin'],
                'sort_order' => 50,
                'version' => '1.0.0',
                'author' => 'AdCompro',
            ],
            [
                'name' => 'notifications',
                'display_name' => 'Notifications',
                'description' => 'Email and in-app notification system',
                'icon' => 'fas fa-bell',
                'category' => 'communication',
                'is_active' => false,
                'is_core' => false,
                'dependencies' => [],
                'routes' => ['notifications'],
                'permissions' => null,
                'sort_order' => 51,
                'version' => '0.8.0',
                'author' => 'AdCompro',
            ],

            // Integrations
            [
                'name' => 'api',
                'display_name' => 'API Access',
                'description' => 'RESTful API for external integrations',
                'icon' => 'fas fa-plug',
                'category' => 'integration',
                'is_active' => false,
                'is_core' => false,
                'dependencies' => [],
                'routes' => ['api'],
                'permissions' => ['super_admin'],
                'sort_order' => 60,
                'version' => '0.1.0',
                'author' => 'AdCompro',
            ],
            [
                'name' => 'webhooks',
                'display_name' => 'Webhooks',
                'description' => 'Configure webhooks for real-time event notifications',
                'icon' => 'fas fa-link',
                'category' => 'integration',
                'is_active' => false,
                'is_core' => false,
                'dependencies' => ['api'],
                'routes' => ['webhooks'],
                'permissions' => ['super_admin'],
                'sort_order' => 61,
                'version' => '0.1.0',
                'author' => 'AdCompro',
            ],
        ];

        foreach ($plugins as $plugin) {
            Plugin::create($plugin);
        }

        echo "Seeded " . count($plugins) . " plugins.\n";
    }
}